### ISSUE TITLE
Business Impact hook fails if nodes are unbound

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-businessprocess#117]
Business Impact hook fails if nodes are unbound

**Comment by mkayontour** [comment]
+1

**Comment by mkayontour** [comment]
I get the same error on both versions 2.0 and 2.1

**Comment by Al2Klimov** [comment]
As investigated w/ @mwaldmueller:

1. The *Business Impact* action in every monitored object's detail view shows only actual business impacts – not *if-then*s.
2. That action indeed doesn't show unbound nodes anyway.

**Comment by Al2Klimov** [comment]
As discussed w/ @mwaldmueller (offline):

If a monitored object is just part of an unbound node, it never "impacts" your business as it's not part of any process of your business. In addition, unbound nodes are (IMO) not the common case in production envs.

@Thomas-Gelf What's your opinion on this thesis of mine?

**Comment by nilmerg** [comment]
My thesis is that this is a non-issue and not of much interest because:

* Unbound nodes are unbound for a reason. i.e. they're not part of a process
* The front-end and the CLI command consider unbound nodes as UNKNOWN while ignoring their node's states entirely
* No-one showed interest in the past 2 years (nearly)
