### ISSUE TITLE
Enhance display of total children counts

### ISSUE THREAD

**Issue by lx183** [Icinga/icingaweb2-module-businessprocess#224]
The new feature from version 2.2.0 showing the children count of every tile does not bring any benefit for my setup. Also some users are confused by this information. Mainly because they are used to the old interface. I would propose to make it optional when configuring a new view.

**Comment by nilmerg** [comment]
Being used to how it has been before is never a good argument. So if that's the only thing why your users are confused, so be it. I'm sure they'll get used to it again. Sorry for being kind of rude here, but if we'd react to every such argument nothing would ever change.

Making it optional is also rather contrary to our front-end design principles. (Configuration only as a last resort, if at all)

Though, it's entirely possible to only show this information if there are multiple children. How the information is displayed may also get changed so that it looks similar to the state counts at the lower right.

**Comment by theFeu** [comment]
I also think that it would make most sense to have it conform to what it looks like in other places (see screenshot)
![image](https://user-images.githubusercontent.com/22217062/75344958-ff064e80-589b-11ea-827c-411d0e4f8582.png)

So it would look something like this:
![image](https://user-images.githubusercontent.com/22217062/75345679-78527100-589d-11ea-9ddc-9f919664c602.png)

**Comment by nilmerg** [comment]
Got changed by #305
