### ISSUE TITLE
Reference to another BP defined in different file is broken 

### ISSUE THREAD

**Issue by lbetz** [Icinga/icingaweb2-module-businessprocess#245]
## Describe the bug
Since 2.2.0 the behaviour of the references to processes in other files changed.

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

Use the following example... 

## Expected behavior
file_1:
bp1 = @file_2:bp2

file_2:
bp2 = host;Service
display 0;bp1;BP1

Doesn't work anymore. Only setting bp2 in file_2 to display 1 works.

**Comment by nilmerg** [comment]
Hi, please provide a working example. You can't reference `bp1` in file_2 with `display`.

**Comment by lbetz** [comment]
Sorry, name and display name were wrong. But what more I can say?

doesn't work anymore:
file_1:
bp1 = @file_2:bp2

file_2:
bp2 = host;Service
display 0;bp2;BP2

still works:
file_1:
bp1 = @file_2:bp2

file_2:
bp2 = host;Service
display 1;bp2;BP2

**Comment by nilmerg** [comment]
Are you able to choose `bp2` during an import in the UI?

**Comment by mdkamijo** [comment]
In a root node you can only import process nodes from the same process, not from other processes (config files). You have to create a root node in your process and in that one you can import process nodes from other processes.
I don't know how it worked before but that's how it seems to work now in 2.2.0.

**Comment by nilmerg** [comment]
I just tried this myself and even got an error trying to view `bp1` in the UI. (Mentioning this would have tremendously helped @lbetz :wink: ) Though the import is clearly working since the service's state from the imported process is properly loaded.

@mdkamijo He's trying to import a sub-node into a root node already. Importing nodes as true root nodes was never possible.
