### ISSUE TITLE
Kinder Prozesse in Businessprocess (rename)

### ISSUE THREAD

**Issue by winter1967** [Icinga/icingaweb2-module-businessprocess#257]
In the german localization, the child process have been renamed in "kinder"; it's in my oppinion no good idea to translate this items word for word.

I thought, there is a solution:
It's possible to edit  tha language file:

application/locale/de_DE/LC_MESSAGES/businessprocess.poapplication/locale/de_DE/LC_MESSAGES/businessprocess.po

But there is a binary file "businessprocess.mo", too. It contains the "kinder", too.

So editing the .po file haven't any success to solve my "kinder" problem.

**Comment by nilmerg** [comment]
Hi,

well, yes, *Kind-Prozess(e)* would be more appropriate. Though, *Child Prozess* is neither acceptable so it must then be *Child Process*. But then we have to rename every *prozess* term so it's also *Business Process* instead of *Business-Prozess*. (Though, I guess *Geschäfts-Prozess* would again be more appropriate.)

So, we have these options:

* *Geschäfts-Prozess(e)* and *Kind-Prozess(e)*
* *Business process(es)* and *Child process(es)*

And, obviously, the latter is the English localization so I think it's not too much to expect someone using this instead of German if that's desired. The first option would use rather standard German terms for this, I wouldn't change that.

**Comment by theFeu** [comment]
Geschäfts-Prozess(e) and Kind-Prozess(e)
sounds like the best option to me.

I feel like we should change that.

**Comment by Wintermute2k6** [comment]
Hi ! Sure this is fixed ?

Still, seems to have a strange naming .. 

![Screen Shot 2021-05-10 at 2 14 45 PM](https://user-images.githubusercontent.com/7203835/117657738-365bd500-b19a-11eb-9c14-b2e371fda650.png)

Screenshot results from the actual Master Branch atm
![Build Status](https://travis-ci.org/Icinga/icingaweb2-module-businessprocess.png?branch=master)

ref/NC/723907

Regards

David

**Comment by nilmerg** [comment]
There's now https://github.com/Icinga/L10n/pull/18 for that.
