### ISSUE TITLE
[dev.icinga.com #12772] API Monitoring

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-businessprocess#57]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12772

**Created by aavinashjha on 2016-09-23 06:30:50 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-23 06:30:50 +00:00 (in Redmine)_

---

Do we have feature for API monitoring which is there in tools like AlertSite which are not only checking the endpoint responsiveness but are also checking if api is performing within the desired threshold and returning right data at the right place.

**Comment by Thomas-Gelf** [comment]
If I didn't misunderstand your question, what you're asking for is basic functionality Icings supports since it's very first released. Please check the [Icinga Plugin API](https://docs.icinga.com/icinga2/latest/doc/module/icinga2/chapter/service-monitoring#service-monitoring-plugin-api) for related details. I'll close this issue, as I have no idea of how this could be related to the Business Process module.
