### ISSUE TITLE
Unable to inherit abstract function

### ISSUE THREAD

**Issue by choonming** [Icinga/icingaweb2-module-businessprocess#81]
Using the latest master build 0b2f4f1c7575d30bf780c3433fef3a1be4802f05. Downloaded and enabled the module with the following error when I browse to the Business Processes menu

`Fatal error: Can't inherit abstract function Icinga\Module\Businessprocess\Html\Renderable::render() (previously declared abstract in Icinga\Web\Widget\AbstractWidget) in /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Web/Component/Tabs.php on line 9`

Using Icinga Web 2.4.0 on RedHat 6.8

@Thomas-Gelf do you have a working tarball of the business process module somewhere?

**Comment by Thomas-Gelf** [comment]
@choonming: I fear php -v is telling 5.3.x - is it?

**Comment by choonming** [comment]
@Thomas-Gelf unfortunately you are right. Its 5.3.3

**Comment by Thomas-Gelf** [comment]
This is a PHP bug dating back to 2011: https://bugs.php.net/bug.php?id=43200 - we've met this before :rage:

Will try to work around this... after lunch :beer:

**Comment by choonming** [comment]
@Thomas-Gelf great! Thanks. Would appreciate it if you can create tags for the releases or update the module zip in the exchange portal as we are deploying it via Puppet ;)

**Comment by Thomas-Gelf** [comment]
Supporting "Enterprise" software makes sooo much fun :boom: 
You're lucky, the in-official schedule for the first official release says "beginning of the next week". We wanted to already tag it this week, but you know... time

**Comment by Thomas-Gelf** [comment]
Just for the sake of completeness: the bug has been filed in 2007, before the first 5.3 release. It has been fixed in 2011 and as far as I remember it was part of 5.3.9, which has been released January 2012. 5.3.x gets no security fixes since mid-2014.

Said all this, I pushed a unit test for this. Unfortunately it didn't fail on [Travis](https://travis-ci.org/Icinga/icingaweb2-module-businessprocess), as their PHP 5.3.x version has not much in common with what you find in RHEL6. But it failed in my local CentOS 6 GitLab-CI runner. Then I worked around the issue with the next commit, tests went green.

Please let me know whether it now works for you - I'm out for lunch. Finally :meat_on_bone: 

Cheers,
Thomas

**Comment by choonming** [comment]
@Thomas-Gelf it works now! Thank you very much. Please do enjoy your lunch! :+1:
